spring:
  h2:
    console:
      enabled: true
      path: /test_db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/Users/sangminlee/spring-tutorial/inflearn/spring-security/form-authentication-dev/db/test_db;AUTO_SERVER=TRUE;
    username: test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # 콘솔에 찍히는 SQL 을 format 해줌
        show_sql: true   # 콘솔에 SQL 을 출력
        jdbc:
          lob:
            non_contextual_creation: true

  thymeleaf:
    cache: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true